import type { ToolProvider } from './types.js'

export const AGENTS: ToolProvider[] = [
  {
    id: 'claude',
    displayName: 'Claude Code',
    repoFileName: 'CLAUDE.md',
    globalFileName: 'CLAUDE.md',
    configDir: '.claude',
    skillsDir: '.claude/skills',
    agentsDir: '.claude/agents',
    detectPaths: ['~/.claude', '~/.claude/CLAUDE.md'],
    detectCommands: ['claude'],
    supportsAgentsMd: false,
  },
  {
    id: 'codex',
    displayName: 'Codex CLI',
    repoFileName: 'AGENTS.md',
    globalFileName: 'AGENTS.md',
    configDir: '.codex',
    skillsDir: '.codex/skills',
    agentsDir: '.codex/agents',
    detectPaths: ['~/.codex'],
    detectCommands: ['codex', 'codex-cli'],
    supportsAgentsMd: true,
  },
  {
    id: 'opencode',
    displayName: 'OpenCode',
    repoFileName: 'AGENTS.md',
    globalFileName: 'AGENTS.md',
    configDir: '.opencode',
    skillsDir: '.opencode/agents',
    agentsDir: '.opencode/agents',
    detectPaths: ['~/.config/opencode'],
    detectCommands: ['opencode'],
    supportsAgentsMd: true,
  },
  {
    id: 'hermes',
    displayName: 'Hermes Agent',
    repoFileName: 'AGENTS.md',
    globalFileName: 'AGENTS.md',
    configDir: '.hermes',
    skillsDir: '.hermes/skills',
    agentsDir: '.hermes/agents',
    detectPaths: ['~/.hermes'],
    detectCommands: ['hermes'],
    supportsAgentsMd: true,
  },
  {
    id: 'gemini',
    displayName: 'Gemini CLI',
    repoFileName: 'GEMINI.md',
    globalFileName: 'GEMINI.md',
    configDir: '.gemini',
    skillsDir: '.gemini/skills',
    agentsDir: '.gemini/agents',
    detectPaths: ['~/.gemini'],
    detectCommands: ['gemini', 'gemini-cli'],
    supportsAgentsMd: false,
  },
  {
    id: 'cursor',
    displayName: 'Cursor',
    repoFileName: '.cursorrules',
    globalFileName: '.cursorrules',
    configDir: '.cursor',
    skillsDir: '.cursor/rules',
    detectPaths: ['~/.cursor'],
    detectCommands: ['cursor'],
    supportsAgentsMd: false,
  },
  {
    id: 'windsurf',
    displayName: 'Windsurf',
    repoFileName: '.windsurfrules',
    globalFileName: '.windsurfrules',
    configDir: '.windsurf',
    detectPaths: ['~/.windsurf'],
    detectCommands: ['windsurf'],
    supportsAgentsMd: false,
  },
  {
    id: 'copilot',
    displayName: 'GitHub Copilot',
    repoFileName: '.github/copilot-instructions.md',
    configDir: '.github',
    detectPaths: ['~/.github'],
    detectCommands: ['github-copilot-cli', 'gh'],
    supportsAgentsMd: false,
  },
  {
    id: 'aider',
    displayName: 'Aider',
    repoFileName: 'CONVENTIONS.md',
    configDir: '.aider',
    detectPaths: ['~/.aider'],
    detectCommands: ['aider'],
    supportsAgentsMd: false,
  },
]
